# default config
baseurl = ""
languageCode = "en-us"
title = "Amy Rossal | Art"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
#google analytics
#googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Pricing"
url = "pricing"
weight = 2

[[menu.main]]
name = "About"
url = "about"
weight = 3

[[menu.main]]
name = "Contact"
url = "contact"
weight = 4

# deult parameter
[params]
#logo = #"https://via.placeholder.com/150"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "Drawings and paintings."
# Preloader
preloader = true
# search
search = true
# about author
author = "Amy Rossal"
author_image = "images/banner-img.png"
bio = "Biography about yourself (optional)"
# Contact info
mobile = "+44 phone number"
email = "email@address"
address = "Physic Address here (optional)"
# Contact Form Action
contact_form_action = "#"
# copyright
copyright = "Copyright &copy; 2021"

# Instagram feed
#[params.instafeed]
#enable = true
#access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
#[params.cookies]
#enable = false
#expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

#[[params.social]]
#icon = "ti-linkedin"
#link = "#"

#[[params.social]]
#icon = "ti-github"
#link = "#"
